Refactor samples with terraform and defaultCredential for Servicebus samples
Azure-Samples/azure-spring-boot-samples pull request #138
Opened 2022-01-04 05:54 UTC by backwind1233

As title

2022-01-13 06:54 UTC, saragluna commented on servicebus/spring-cloud-azure-starter-integration-servicebus/multiple-namespaces/terraform/main.tf
> +  namespace_id      = azurerm_servicebus_namespace.servicebus_namespace_02.id
format

2022-01-17 08:12 UTC, saragluna requested changes

2022-01-17 08:14 UTC, backwind1233 commented on servicebus/spring-cloud-azure-starter-servicebus-jms/servicebus-jms-topic/src/main/resources/application.yaml
> +      topic-client-id: ${TOPIC_CLIENT_ID}
> The topic-client-id should be irrelevant to terraform
Agree

2022-01-17 11:24 UTC, saragluna approved these changes
LGTM

2022-01-17 11:24 UTC, merged