servicebus jms queue sample update
Azure-Samples/azure-spring-boot-samples pull request #158
Opened 2022-01-19 02:57 UTC by jialigit

## Purpose

* ...

## Does this introduce a breaking change?

```
[ ] Yes
[ ] No
```

## Pull Request Type
What kind of change does this Pull Request introduce?

```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Documentation content changes
[ ] Other... Please describe:
```

## How to Test
*  Get the code

```
git clone [repo-address]
cd [repo-name]
git checkout [branch-name]
npm install
```

* Test the code

```
```

## What to Check
Verify that the following are valid
* ...

## Other Information

2022-01-19 03:49 UTC, backwind1233 commented
@yiliuTo please help review this PR.

2022-01-20 07:14 UTC, yiliuTo requested changes

2022-01-20 07:14 UTC, yiliuTo commented on servicebus/spring-cloud-azure-starter-servicebus-jms/servicebus-jms-queue/src/main/java/com/azure/spring/sample/jms/queue/SyncQueueSendController.java
> +        objectMessage.setJMSReplyTo(connectionFactory.createContext().createTemporaryQueue());
what is the temporary queue here mean? will it create a queue in Service Bus? And we can comment here to introduce the meaning of message properties we configured.

2022-01-20 07:14 UTC, yiliuTo commented on servicebus/spring-cloud-azure-starter-servicebus-jms/servicebus-jms-queue/src/main/java/com/azure/spring/sample/jms/queue/SyncQueueSendController.java
> +            objectMessage, User.class); //this operation seems to be blocking + sync
we shouldn't have "seems to be" here

2022-01-20 07:14 UTC, yiliuTo commented on servicebus/spring-cloud-azure-starter-servicebus-jms/servicebus-jms-queue/src/main/resources/application.yaml
> +queuename: que001
Let's follow unified property naming schema and use kebab here

2022-01-20 07:16 UTC, yiliuTo commented
We can update this sample and introduce the usage of caching and pooled connection factory

2022-01-20 07:19 UTC, backwind1233 commented on servicebus/spring-cloud-azure-starter-servicebus-jms/servicebus-jms-queue/README.md
> +Navigate to the project root directory, then run the maven command:
we can update the template and then update all the descriptions here.
issue [link](https://github.com/Azure-Samples/azure-spring-boot-samples/issues/149)

please revert it here.

2022-01-20 07:20 UTC, backwind1233 commented on servicebus/spring-cloud-azure-starter-servicebus-jms/servicebus-jms-queue/README.md
> +1. Verify in your app's logs that a similar message was posted:
similar messages were posted

2022-01-20 07:20 UTC, backwind1233 commented on servicebus/spring-cloud-azure-starter-servicebus-jms/servicebus-jms-queue/README.md
> +3. [Optional] Verify in your app's logs that a similar message was posted:
same here

2022-01-20 07:23 UTC, backwind1233 commented on servicebus/spring-cloud-azure-starter-servicebus-jms/servicebus-jms-queue/src/main/java/com/azure/spring/sample/jms/queue/QueueSendController.java
>  public class QueueSendController {
The Controller can be remained I think,  it has a post request.

2022-03-21 02:18 UTC, jialigit commented
I should propose different pr for different issues. So this closed for now.

2022-03-21 02:18 UTC, closed without merging