add link to reference doc
Azure-Samples/azure-spring-boot-samples pull request #199
Opened 2022-02-22 02:51 UTC by Netyyyy

As title.

2022-02-22 02:57 UTC, backwind1233 commented on eventhubs/spring-cloud-azure-stream-binder-eventhubs/eventhubs-binder/README.md
> +###[Enable sync message](https://microsoft.github.io/spring-cloud-azure/4.0.0-beta.4/4.0.0-beta.4/reference/html/index.html#producer-properties)
![image](https://user-images.githubusercontent.com/4465723/155054855-aaaada94-60cb-416a-9923-71131e48b7fe.png)
check format here.

2022-02-22 08:14 UTC, yiliuTo requested changes

2022-02-22 08:14 UTC, yiliuTo commented on servicebus/spring-cloud-azure-starter-integration-servicebus/single-namespace/README.md
> +[Set Service Bus message headers](https://microsoft.github.io/spring-cloud-azure/4.0.0-beta.4/4.0.0-beta.4/reference/html/index.html#si-sb-headers)
Let's add some simple introduction here.

2022-02-22 08:14 UTC, yiliuTo commented on servicebus/spring-cloud-azure-stream-binder-servicebus/servicebus-multibinders/README.md
> +
Let's add features like the way you update event hub binder readme, and the features should include: sync, resource provisioning, parititioning, session, error channels, message headers. And due to we don't show how to work in sync mode in this sample, thus we could only add text introduction without the code.

2022-02-22 08:14 UTC, yiliuTo commented on servicebus/spring-cloud-azure-stream-binder-servicebus/servicebus-queue-binder/README.md
> +### [Set Service Bus message headers](https://microsoft.github.io/spring-cloud-azure/4.0.0-beta.4/4.0.0-beta.4/reference/html/index.html#scs-sb-headers)
same here.

2022-02-22 08:14 UTC, yiliuTo commented on servicebus/spring-cloud-azure-stream-binder-servicebus/servicebus-topic-binder/README.md
> +#### [Service Bus Producer Properties](https://microsoft.github.io/spring-cloud-azure/4.0.0-beta.4/4.0.0-beta.4/reference/html/index.html#producer-properties-2)
same here

2022-02-22 08:14 UTC, yiliuTo commented on servicebus/spring-cloud-azure-stream-binder-servicebus/servicebus-multibinders/README.md
> +
Need we also udpate the event hub muti-binder sample?

2022-02-23 02:09 UTC, Netyyyy commented on eventhubs/spring-cloud-azure-stream-binder-eventhubs/eventhubs-binder/README.md
> +[usage sample](https://microsoft.github.io/spring-cloud-azure/4.0.0-beta.4/4.0.0-beta.4/reference/html/index.html#batch-consumer-support-2)
add resource provision on @https://github.com/microsoft/spring-cloud-azure/pull/857

2022-02-23 02:10 UTC, Netyyyy commented on eventhubs/spring-cloud-azure-stream-binder-eventhubs/eventhubs-binder/README.md
> +[usage sample](https://microsoft.github.io/spring-cloud-azure/4.0.0-beta.4/4.0.0-beta.4/reference/html/index.html#batch-consumer-support-2)
> We should introduce anther feature of resource provisioning, which is similar with https://github.com/Azure-Samples/azure-spring-boot-samples/tree/main/eventhubs/azure-spring-cloud-stream-binder-eventhubs/eventhubs-binder#enable-auto-create but we only support provisioning resources of event hub and consumer group.
> 
> And the necessary configuration are :
> 
> ```
> spring:
>   cloud:
>     azure:
>       credential:
>         tenant-id: tenant
>       profile:
>         subscription-id: id
>       eventhubs:
>         resource:
>           resource-group: group
> ```
> 
> Please also help to add such content in the reference doc, thanks.

add resource provision on @https://github.com/microsoft/spring-cloud-azure/pull/857

2022-02-28 08:57 UTC, yiliuTo requested changes

2022-02-28 08:57 UTC, yiliuTo commented on servicebus/spring-cloud-azure-starter-integration-servicebus/single-namespace/README.md
> +users can get all the supported ServiceBus message headers [here](https://microsoft.github.io/spring-cloud-azure/4.0.0-beta.4/4.0.0-beta.4/reference/html/index.html#si-sb-headers) to configure.
Should be "Users" instead "users"

2022-02-28 08:57 UTC, yiliuTo commented on servicebus/spring-cloud-azure-stream-binder-servicebus/servicebus-multibinders/README.md
> +### ERROR CHANNEL
same here

2022-02-28 08:57 UTC, yiliuTo commented on servicebus/spring-cloud-azure-stream-binder-servicebus/servicebus-multibinders/README.md
> +[Auto create resource](https://microsoft.github.io/spring-cloud-azure/4.0.0-beta.4/4.0.0-beta.4/reference/html/index.html#resource-provision-2): queue, topic, subscription
same here, let's write a complete and formor sentence

2022-02-28 08:57 UTC, yiliuTo commented on servicebus/spring-cloud-azure-stream-binder-servicebus/servicebus-multibinders/README.md
> +ServiceBus binder supports partitioning by allowing setting partition key and session id in the message header. [Here](https://microsoft.github.io/spring-cloud-azure/4.0.0-beta.4/4.0.0-beta.4/referen
Should be "Service Bus"

2022-02-28 08:57 UTC, yiliuTo commented on servicebus/spring-cloud-azure-stream-binder-servicebus/servicebus-multibinders/README.md
> +ServiceBus binder supports consumer error channel, producer error channel and global default error channel, click [here](https://microsoft.github.io/spring-cloud-azure/4.0.0-beta.4/4.0.0-beta.4/refer
same here

2022-02-28 08:57 UTC, yiliuTo commented on servicebus/spring-cloud-azure-stream-binder-servicebus/servicebus-queue-binder/README.md
> +[Auto create resource](https://microsoft.github.io/spring-cloud-azure/4.0.0-beta.4/4.0.0-beta.4/reference/html/index.html#resource-provision-2): queue, topic, subscription
same here.

2022-02-28 08:57 UTC, yiliuTo commented on servicebus/spring-cloud-azure-stream-binder-servicebus/servicebus-queue-binder/README.md
> +
same here

2022-02-28 08:57 UTC, yiliuTo commented on servicebus/spring-cloud-azure-stream-binder-servicebus/servicebus-queue-binder/README.md
> +ServiceBus binder supports consumer error channel, producer error channel and global default error channel, click [here](https://microsoft.github.io/spring-cloud-azure/4.0.0-beta.4/4.0.0-beta.4/refer
same here

2022-02-28 08:57 UTC, yiliuTo commented on servicebus/spring-cloud-azure-stream-binder-servicebus/servicebus-topic-binder/README.md
> +ServiceBus binder supports partitioning by allowing setting partition key and session id in the message header. [Here](https://microsoft.github.io/spring-cloud-azure/4.0.0-beta.4/4.0.0-beta.4/referen
same here

2022-02-28 08:57 UTC, yiliuTo commented on servicebus/spring-cloud-azure-stream-binder-servicebus/servicebus-topic-binder/README.md
> +ServiceBus binder supports message sessions. [Here](https://microsoft.github.io/spring-cloud-azure/4.0.0-beta.4/4.0.0-beta.4/reference/html/index.html#session-support) shows how to set session id of
same here

2022-02-28 08:57 UTC, yiliuTo commented on servicebus/spring-cloud-azure-stream-binder-servicebus/servicebus-topic-binder/README.md
> +### ERROR CHANNEL
same here and below

2022-02-28 08:57 UTC, yiliuTo commented on servicebus/spring-cloud-azure-stream-binder-servicebus/servicebus-queue-binder/README.md
> +### ERROR CHANNEL
same here

2022-03-01 08:02 UTC, yiliuTo requested changes

2022-03-01 08:02 UTC, yiliuTo commented on eventhubs/spring-cloud-azure-stream-binder-eventhubs/eventhubs-binder/README.md
> +The binder supports Event Hubs partitioning by allowing setting partition key and session id in the message header. This section introduces how to set partition key for messages.
Sorry there is wrong information I pass to you. There are some differences for partitioning support between Event Hubs and Service Bus. Event Hubs only support partition key and id, so there is no session id for eh. And the way to configure partition information is also different from sb, so let's change these several parts:
1. Change the title from "Partition key support" to "Partition support".
2. Delete below content and code, only remain "The binder supports Event Hubs partitioning by allowing setting partition key and id. Please refer to the [reference doc](https://microsoft.github.io/spring-cloud-azure/4.0.0-beta.4/4.0.0-beta.4/reference/html/index.html#partitioning-support-2) for more details."
3. Remove below section of "Session support"

2022-03-01 08:02 UTC, yiliuTo commented on eventhubs/spring-cloud-azure-stream-binder-eventhubs/eventhubs-multibinders/README.md
> +#### Partition key support
Let's remove the whole section of "Partition key support"

2022-03-01 08:02 UTC, yiliuTo commented on eventhubs/spring-cloud-azure-stream-binder-eventhubs/eventhubs-multibinders/README.md
> +#### Session support
same here, remove this section.

2022-03-01 08:29 UTC, yiliuTo approved these changes
LGTM

2022-03-01 08:36 UTC, merged