Add section in readme for debugging samples
Azure-Samples/azure-spring-boot-samples pull request #212
Opened 2022-03-07 06:41 UTC by hui1110

As title.

2022-03-14 02:06 UTC, backwind1233 commented on eventhubs/spring-cloud-azure-starter-integration-eventhubs/eventhubs-integration/README.md
> +### Run the program directly
I suggest not using `program` here, use sample instead.

2022-03-14 02:07 UTC, backwind1233 commented on eventhubs/spring-cloud-azure-starter-integration-eventhubs/eventhubs-integration/README.md
> +### Run the program in debug mode
use with title format `Run the Program in Debug Mode`

2022-03-14 02:07 UTC, backwind1233 commented on eventhubs/spring-cloud-azure-starter-integration-eventhubs/eventhubs-integration/README.md
> +If you want to run the program in debug mode, you can save the output value.
better add a picture to demonstrate here.

2022-03-14 02:09 UTC, backwind1233 commented on eventhubs/spring-cloud-azure-starter-integration-eventhubs/eventhubs-integration/README.md
> +You can debug your program by adding the saved output values or finding the required parameters in the `terraform.tfstate` file in the program's terraform directory and adding them to the tool's envi
suggest delete this
<img width="949" alt="image" src="https://user-images.githubusercontent.com/4465723/158092709-bb11bbad-3c6c-4f4e-8765-142e404eeed4.png">


and better add a pic to demonstrate how to do it.

2022-03-14 02:09 UTC, backwind1233 requested changes

2022-03-14 02:09 UTC, backwind1233 commented on eventhubs/spring-cloud-azure-starter-integration-eventhubs/eventhubs-integration/README.md
> +### Run the program in debug mode
replace "program", it's too general.

2022-03-14 03:23 UTC, backwind1233 commented on eventhubs/spring-cloud-azure-starter-integration-eventhubs/eventhubs-integration/README.md
> +### Run the sample directly
Run the Sample Directly

2022-03-14 03:28 UTC, backwind1233 requested changes

2022-03-14 03:28 UTC, backwind1233 commented on eventhubs/spring-cloud-azure-starter-integration-eventhubs/eventhubs-integration/README.md
> +![image](resource/output.png)
it's hard work if we place a png file in each sample, I am wondering whether we can do it just like below
<img width="853" alt="image" src="https://user-images.githubusercontent.com/4465723/158099876-41852903-cfa3-4874-ba64-4452f47f6e8c.png">

2022-03-14 06:07 UTC, backwind1233 commented on eventhubs/spring-cloud-azure-starter-integration-eventhubs/eventhubs-integration/README.md
> +If you want to run the program in debug mode, you can save the output value.
program --> sample

2022-03-15 05:47 UTC, saragluna commented on cache/spring-cloud-azure-starter/spring-cloud-azure-sample-cache/README.md
> +### Run the sample Directly
how about change to Run with Maven

2022-03-15 05:48 UTC, saragluna commented on cache/spring-cloud-azure-starter/spring-cloud-azure-sample-cache/README.md
> +### Run the sample in Debug Mode
how about changing to Run in IDEs

2022-03-16 06:00 UTC, backwind1233 approved these changes
LGTM

2022-03-16 06:12 UTC, merged