Fix readme doc issues of jca
Azure-Samples/azure-spring-boot-samples pull request #215
Opened 2022-03-08 10:37 UTC by backwind1233

2022-03-08 10:41 UTC, backwind1233 commented
Link with https://github.com/Azure/azure-sdk-for-java/issues/27329, finding doc errors why addressing the issue.

2022-03-08 10:43 UTC, backwind1233 commented
@chenrujun please help review this PR.

2022-03-08 23:37 UTC, chenrujun requested changes

2022-03-08 23:37 UTC, chenrujun commented on keyvault/azure-spring-boot-starter-keyvault-certificates/keyvault-certificates-client-side/README.md
> +   > Attention: The service principal must be configured with get and list permissions of certificate, key, secret.
```
key: get
secret: get
certificate: get, list
```
For key and secret, only `get` permission is required.

2022-03-08 23:37 UTC, chenrujun commented on keyvault/azure-spring-boot-starter-keyvault-certificates/keyvault-certificates-server-side/README.md
> +   > Attention: The service principal must be configured with get and list permissions of certificate, key, secret.
Same here.

2022-03-10 02:02 UTC, backwind1233 commented on keyvault/azure-spring-boot-starter-keyvault-certificates/keyvault-certificates-server-side/README.md
> +   > Attention: The service principal must be configured with get and list permissions of certificate, key, secret.
updated

2022-03-10 05:43 UTC, chenrujun commented on keyvault/azure-spring-boot-starter-keyvault-certificates/keyvault-certificates-client-side/README.md
> +   > Key Permissions: configure with get permission.
Nit: `get` -> `**get**`.

2022-03-10 05:43 UTC, chenrujun commented on keyvault/azure-spring-boot-starter-keyvault-certificates/keyvault-certificates-client-side/README.md
> +   > Secret Permissions: configure with get permission.
Same here.

2022-03-10 05:43 UTC, chenrujun commented on keyvault/azure-spring-boot-starter-keyvault-certificates/keyvault-certificates-server-side/README.md
> +   > Key Permissions: configure with get permission.
Same here.

2022-03-10 05:43 UTC, chenrujun commented on keyvault/azure-spring-boot-starter-keyvault-certificates/keyvault-certificates-server-side/README.md
> +   > Secret Permissions: configure with get permission.
Here.

2022-03-10 05:46 UTC, chenrujun approved these changes

2022-03-14 01:13 UTC, backwind1233 commented on keyvault/azure-spring-boot-starter-keyvault-certificates/keyvault-certificates-server-side/README.md
> +   > Secret Permissions: configure with get permission.
all updated

2022-03-14 01:34 UTC, merged

2022-03-14 01:34 UTC, chenrujun reviewed
LGTM.