Add sample:servicebus-queue-binder-arm
Azure-Samples/azure-spring-boot-samples pull request #225
Opened 2022-03-18 01:58 UTC by Netyyyy

As title.

2022-03-18 03:47 UTC, backwind1233 commented
<img width="1252" alt="image" src="https://user-images.githubusercontent.com/4465723/158933926-04309643-3480-470b-ac49-242a255837f6.png">
@Netyyyy 
The sample runs failed, can you check this?

2022-03-18 03:48 UTC, backwind1233 commented on servicebus/spring-cloud-azure-stream-binder-servicebus/servicebus-queue-binder-arm/terraform/main.tf
> +      source  = "hashicorp/random"
do we need this provider here?

2022-03-18 03:54 UTC, backwind1233 commented on servicebus/spring-cloud-azure-stream-binder-servicebus/servicebus-queue-binder-arm/terraform/main.tf
> +  display_name = "servicebus-queue-binder-arm"
add a random string here for the display_name

like display_name = "servicebus-queue-binder-arm-xxxxx"

2022-03-18 03:57 UTC, backwind1233 commented on servicebus/spring-cloud-azure-stream-binder-servicebus/servicebus-queue-binder-arm/terraform/main.tf
> +  display_name = "servicebus-queue-binder-arm"
you can refer to https://registry.terraform.io/providers/hashicorp/random/latest/docs

2022-03-18 04:01 UTC, backwind1233 commented on servicebus/spring-cloud-azure-stream-binder-servicebus/servicebus-queue-binder-arm/terraform/main.tf
> +  role_definition_name = "Contributor"
<img width="734" alt="image" src="https://user-images.githubusercontent.com/4465723/158935010-1d61a2d6-f70e-4c14-bea5-219b0a0674d4.png">

can you double-check this, it seems "Contributor" has no data plane permissions

2022-03-18 04:01 UTC, backwind1233 requested changes
can you run the sample again?

2022-03-18 05:45 UTC, saragluna commented on servicebus/spring-cloud-azure-stream-binder-servicebus/servicebus-queue-binder-arm/README.md
> +# Spring Cloud Azure Stream Binder for Service Bus queue by ARM Authentication Sample shared library for Java
Spring Cloud Azure Stream Binder for Service Bus Queue by retrieving connecting string via ARM

2022-03-18 05:53 UTC, saragluna requested changes

2022-03-18 05:53 UTC, saragluna commented on servicebus/spring-cloud-azure-stream-binder-servicebus/servicebus-queue-binder-arm/README.md
> +Azure Service Bus queue by Azure Resource Manager Authentication.
Azure Service Bus Queue by retrieving connection string via ARM.

2022-03-18 05:53 UTC, saragluna commented on servicebus/spring-cloud-azure-stream-binder-servicebus/servicebus-queue-binder-arm/README.md
> +You will build an application using Spring Cloud Stream to send and receive messages for Azure Service Bus Queue, and  a service principal for this application.
You will build an application using Spring Cloud Stream to send and receive messages for Azure Service Bus Queue. This sample will
- Create a Service Bus queue and a service principal and assign the `Contributor` role of the service bus to the service principal.
- Connect to the ARM using the service principal and retrieve the connection string of the service bus.
- Connect to the Service Bus queue to send and receive messages.

2022-03-18 05:53 UTC, saragluna commented on servicebus/spring-cloud-azure-stream-binder-servicebus/servicebus-queue-binder-arm/pom.xml
> +    </dependency>
we don't need this, the `spring-cloud-azure-stream-binder-servicebus` has already depended on it IIRC.

2022-03-18 05:53 UTC, saragluna commented on servicebus/spring-cloud-azure-stream-binder-servicebus/servicebus-queue-binder-arm/terraform/main.tf
> +resource "azurerm_role_assignment" "role_servicebus_data_contributor" {
`role_servicebus_contributor`, this role is not a data role

2022-03-18 06:14 UTC, saragluna commented on servicebus/spring-cloud-azure-stream-binder-servicebus/servicebus-queue-binder-arm/pom.xml
> +  <artifactId>spring-cloud-azure-sample-stream-binder-servicebus-queue-arm</artifactId>
please also add this module into the aggregator pom, https://github.com/Azure-Samples/azure-spring-boot-samples/blob/spring-cloud-azure_4.0.0-beta.4/pom.xml.

2022-03-18 06:17 UTC, saragluna commented on servicebus/spring-cloud-azure-stream-binder-servicebus/servicebus-queue-binder-arm/README.md
> +## Run Locally
Yonghui did some changes to this part, please also apply to this PR. https://github.com/Azure-Samples/azure-spring-boot-samples/pull/212

2022-03-18 06:20 UTC, saragluna commented
> <img alt="image" width="1252" src="https://user-images.githubusercontent.com/4465723/158933926-04309643-3480-470b-ac49-242a255837f6.png">
> 
> @Netyyyy The sample runs failed, can you check this?

@backwind1233, I can run it locally.

2022-03-18 08:22 UTC, backwind1233 commented
also, please add the new module in the root readme. @Netyyyy

2022-03-18 09:35 UTC, saragluna approved these changes
LGTM.

2022-03-21 00:57 UTC, backwind1233 approved these changes
LGTM

2022-03-21 00:58 UTC, merged