Add OpenAI starter sample
Azure-Samples/azure-spring-boot-samples pull request #711
Opened 2023-07-14 00:31 UTC by Netyyyy

## Purpose
Add OpenAI starter sample

## Does this introduce a breaking change?

```
[ ] Yes
[x] No
```

## Pull Request Type
What kind of change does this Pull Request introduce?

```
[ ] Bugfix
[x] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Documentation content changes
[ ] Other... Please describe:
```

2023-07-14 01:37 UTC, saragluna requested changes

2023-07-14 01:37 UTC, saragluna commented on openai/spring-cloud-azure-starter-openai/spring-cloud-azure-openai-sample/src/main/java/com/azure/spring/openai/sample/OpenAIController.java
> +import org.springframework.web.bind.annotation.RequestBody;
optimize the imports

2023-07-14 01:37 UTC, saragluna commented on openai/spring-cloud-azure-starter-openai/spring-cloud-azure-openai-sample/src/main/java/com/azure/spring/openai/sample/OpenAIController.java
> +    @ResponseBody
I don't think the `@ResponseBody` is required here https://www.baeldung.com/spring-controller-vs-restcontroller#overview.

2023-07-17 01:52 UTC, stliu commented on openai/spring-cloud-azure-starter-openai/spring-cloud-azure-openai-sample/src/main/java/com/azure/spring/openai/sample/OpenAIController.java
> +    private OpenAIClient client;
we should alway promote spring's best practice in our sample, in this case,, we should use constructor based injection

2023-07-21 06:27 UTC, Netyyyy commented
@saragluna , please help take a look, thanks.

2023-07-21 09:33 UTC, saragluna approved these changes

2023-07-24 00:43 UTC, merged

2023-07-27 14:23 UTC, backwind1233 commented
@Netyyyy FYI this [link](https://github.com/Azure-Samples/azure-spring-boot-samples/pull/39) to you if needed.