Add redis samples
Azure-Samples/azure-spring-boot-samples pull request #745
Opened 2024-06-06 08:51 UTC by Netyyyy

Since `spring-cloud-azure-starter-data-redis-lettuce` is ready, add samples for passwordlless and non-passwordless

2024-06-06 08:57 UTC, saragluna requested changes

2024-06-06 08:57 UTC, saragluna commented on cache/spring3-sample/spring-cloud-azure-redis-sample/pom.xml
> +    <dependency>
Do we need this dependency?

2024-06-12 00:19 UTC, Netyyyy commented on cache/spring3-sample/spring-cloud-azure-redis-sample/pom.xml
> +    <dependency>
yes, this sample use ARM to authorize.

2024-06-18 02:41 UTC, saragluna approved these changes

2024-06-18 08:35 UTC, merged