Update the readme and properties configuration of servicebus multibinders.
Azure-Samples/azure-spring-boot-samples pull request #93
Opened 2021-11-22 09:50 UTC by hui1110

Modify the directory of servicebus queue multibinders.
Update the readme and properties configuration of servicebus multibinders.

2021-11-22 10:22 UTC, moarychan requested changes

2021-11-22 10:22 UTC, moarychan commented on servicebus/spring-cloud-azure-stream-binder-servicebus/servicebus-multibinders/src/main/resources/application-sp.yaml
>                      connection-string: [ servicebus-namespace-2-connection-string ]
It's better to change to AZURE_XXX_SERVICE_CONNECTION_STRING.

2021-11-23 05:08 UTC, yiliuTo requested changes

2021-11-23 05:08 UTC, yiliuTo commented on servicebus/spring-cloud-azure-stream-binder-servicebus/servicebus-topic-binder/src/main/resources/application-sp.yaml
>  #    Uncomment below configurations if you want to enable auto creating resources.
Please remove the configuration of auto-creating-resources in all the configuration files and readme.

2021-11-23 05:08 UTC, yiliuTo commented on servicebus/spring-cloud-azure-stream-binder-servicebus/servicebus-topic-binder/src/main/resources/application-mi.yaml
> +        managed-identity-client-id: ${AZURE_MANAGED_IDENTITY_CLIENT_ID]
change ${AZURE_MANAGED_IDENTITY_CLIENT_ID] to ${AZURE_MANAGED_IDENTITY_CLIENT_ID}, same for other places

2021-11-23 05:14 UTC, yiliuTo requested changes

2021-11-23 05:14 UTC, yiliuTo commented on servicebus/spring-cloud-azure-stream-binder-servicebus/servicebus-multibinders/pom.xml
> +  <version>1.0.0</version> <!-- {com.azure.spring:spring-cloud-azure-sample-stream-binder-servicebus-multiple;dependency} -->
you can just delete the whole lable: <!-- {com.azure.spring:spring-cloud-azure-sample-stream-binder-servicebus-multiple;dependency} -->. 
Same for other pom.xml.

2021-11-23 05:14 UTC, yiliuTo commented on servicebus/spring-cloud-azure-stream-binder-servicebus/servicebus-multibinders/pom.xml
> +        <version>1.14.0</version> <!-- {com.microsoft.azure:azure-webapp-maven-plugin;external_dependency} -->
please help to delete the whole <build> part.

2021-11-23 05:14 UTC, yiliuTo commented on servicebus/spring-cloud-azure-stream-binder-servicebus/servicebus-queue-binder/pom.xml
> +        <version>1.14.0</version> <!-- {com.microsoft.azure:azure-webapp-maven-plugin;external_dependency} -->
same here

2021-11-23 05:14 UTC, yiliuTo commented on servicebus/spring-cloud-azure-stream-binder-servicebus/servicebus-queue-binder/pom.xml
> +  <version>1.0.0</version> <!-- {com.azure.spring:spring-cloud-azure-sample-stream-binder-servicebus-queue;dependency} -->
same here

2021-11-23 06:16 UTC, yiliuTo approved these changes
LGTM

2021-11-23 06:16 UTC, merged